#!/usr/bin/env bash

wallpapers_path="${HOME}/.dotfiles/wallpaper"

while true; do
  swaybg -i $(find $wallpapers_path -type f -not -path "$wallpapers_path/.git*" | shuf -n 1) -m fill
  sleep 29m
done
sleep 1m
